home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),


]

reservation/urls.py
from django.urls import path
from . import views


app_name = 'reservation'

urlpatterns = [

    path('', views.reserve_table, name='reserve_table'),
    path('register/', views.registerpage, name='register'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('create_order/', views.create_order, name='create_order'),
    path('update_reservations/<pk>/', views.update_reservations,
         name='update_reservations'),
    path('delete_reservations/<pk>/', views.delete_reservations,
         name='delete_reservations'),
    path('<pk>/', views.customer_table, name='customer_table'),

]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls', namespace='menu')),
    path('aboutRestaurant/', include('aboutRestaurant.urls',
         namespace='aboutRestaurant')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('reserve_table/', include('reservation.urls', namespace='reservation')),
    path('', include('home.urls', namespace='home')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'home.views.error_404'

reservation/models.py
from django.db import models
from django.contrib.auth.models import User

time_choices = (
    ("07:00", "07:00"),
    ("08:00", "08:00"),
    ("09:00", "09:00"),
    ("10:00", "10:00"),
    ("11:00", "11:00"),
    ("12:00", "12:00"),
    ("13:00", "13:00"),
    ("14:00", "14:00"),
    ("15:00", "15:00"),
    ("16:00", "16:00"),
    ("17:00", "17:00"),
    ("18:00", "18:00"),
    ("19:00", "19:00"),
    ("20:00", "20:00"),
    ("21:00", "21:00"),
)


class Customer(models.Model):

    """ Model for customer """

    name = models.CharField(max_length=50, null=True)
    email = models.EmailField(default='')
    phone = models.CharField(max_length=13, default='')
    owner = models.IntegerField(blank=False, default=1)

    def __str__(self):
        return self.name


class Table(models.Model):

    """ Model for Table """

    table_name = models.CharField(
        max_length=20, default="New table", unique=True)
    max_no_people = models.IntegerField()

    def __str__(self):
        return self.table_name


class Reservation(models.Model):

    """ Model for Reservation """

    STATUS = (("pending", "pending"),
              ("confirmed", "confirmed"),
              ("rejected", "rejected"),
              ("expired", "expired"))

    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name="customer", null=True)

    table = models.ForeignKey(
        Table, on_delete=models.CASCADE,
        related_name="table_booked", null=True)

    guests_choices = ((1, "1 person"), (2, "2 people"),
                      (3, "3 people"), (4, "4 people"))

    persons = models.IntegerField(choices=guests_choices, default=1)

    date = models.DateField()

    time = models.CharField(
        max_length=10, choices=time_choices, default='12:00')

    status = models.CharField(
        max_length=200, null=True, choices=STATUS, default='pending')

    def __str__(self):
        return str(self.time)

reservation/forms.py
""" Import module from django """
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Reservation, Customer


class CustomerForm(forms.ModelForm):

    """" Form for customer Phone Number placeholder """

    phone = forms.CharField(widget=forms.TextInput(
                            attrs={'placeholder': ('Please'
                                   'enter in +44 format')}))
    name = forms.CharField(required=False)

    class Meta:

        """ Add meta class for Name, Email and Date """

        model = Customer
        fields = ('name', 'email', 'phone')

    def clean_name(self, *args, **kwargs):
        """ Validate Name field  """

        name = self.cleaned_data.get("name")
        if not name.isalpha() and name.isnumeric():
            raise forms.ValidationError('Please enter valid name')
        if len(name) == '' or len(name) < 1:
            raise forms.ValidationError("Name field is required.")
        if '@' in name or '-' in name or '|' in name or '*' in name:
            raise forms.ValidationError(
                "Name should not have special characters.")
        return name


class ReservationForm(forms.ModelForm):

    """" Form for Reservation Date placeholder """

    date = forms.DateField()

    class Meta:

        """ Add meta class for Persons, Time, Date """

        model = Reservation
        fields = ['persons', 'time', 'date']


class CreateUserForm(UserCreationForm):

    """ create class for users form  """

    email = forms.EmailField()
    first_name = forms.CharField(max_length=50, required=False)
    last_name = forms.CharField(max_length=50, required=False,)

    class Meta:

        """ Add meta class for Register form  """

        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'password1', 'password2']

    def clean_first_name(self, *args, **kwargs):
        """ Validate First name field  """

        f_name = self.cleaned_data.get("first_name")
        if not f_name.isalpha() and f_name.isnumeric():
            raise forms.ValidationError('Please enter valid first name')
        if len(f_name) == '' or len(f_name) < 1:
            raise forms.ValidationError("First name field is required.")
        if '@' in f_name or '-' in f_name or '|' in f_name or '*' in f_name:
            raise forms.ValidationError(
                "First name should not have special characters.")
        return f_name

    def clean_last_name(self, *args, **kwargs):
        """ Validate Last name field  """

        l_name = self.cleaned_data.get("last_name")
        if not l_name.isalpha() and l_name.isnumeric():
            raise forms.ValidationError('Please enter valid last name')
        if len(l_name) == '' or len(l_name) < 1:
            raise forms.ValidationError("Last name field is required.")
        if '@' in l_name or '-' in l_name or '|' in l_name or '*' in l_name:
            raise forms.ValidationError(
                "Last name should not have special characters.")

        return l_name

reservation/views.py
""" Import Django contrib, models and forms """
import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Table, Customer, Reservation
from .forms import ReservationForm, CustomerForm, CreateUserForm
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags


def registerpage(request):
    """ Registration form for user """

    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            first_name = request.POST.get('first_name')
            email = request.POST.get('email')
            html_message = render_to_string(
                'Reservation/register_email.html', {'name': first_name})
            plain_message = strip_tags(html_message)

            send_mail(
                'From: Mochi Restaurant',
                plain_message,
                'mochi_restaurant@site.com',
                [email],
                fail_silently=False,
                html_message=html_message,
            )
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)

            messages.success(
                request, f'{username} your account has been created ')

            return redirect('/')

    context = {
        'form': form,
    }
    return render(request, 'Reservation/register.html', context)


def loginpage(request):
    """ Login function for user  """

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Username OR password incorrect')

    context = {}
    return render(request, 'Reservation/login.html', context)


def logoutuser(request):
    """" Logout function for users """

    logout(request)
    return redirect('/')


def check_table_availabilty(customer_requested_time, customer_requested_date):
    """ check availability against Reservation model using customer input """

    # Check to see how many bookings exist at that time/date
    no_tables_booked = len(Reservation.objects.filter(
        time=customer_requested_time,
        date=customer_requested_date, status="confirmed"))
    # Return number of tables
    return no_tables_booked


def check_table_in_restaurant():
    """ Retrieves the number of tables in the table model """
    max_tables = len(Table.objects.all())
    return max_tables


@login_required(login_url='/reserve_table/login')
def create_order(request):
    """Create function for get Reservation form """

    form = ReservationForm()
    customer_form = CustomerForm()
    if request.method == 'POST':
        # Get post data from forms
        customer_form = CustomerForm(data=request.POST)
        form = ReservationForm(data=request.POST)

        if customer_form.is_valid() and form.is_valid():
            # Retreive information from forms
            customer_requested_date = request.POST.get('date')
            customer_requested_time = request.POST.get('time')
            customer_requested_guests = request.POST.get('persons')
            customer_name = request.POST.get('name')

            # Send mail to the user when user send booking request
            from_email = request.user.email
            email = request.POST.get('email')
            html_message = render_to_string(
                'Reservation/create_booking_email.html',
                {'name': request.user.first_name})
            plain_message = strip_tags(html_message)

            send_mail(
                'From: Mochi Restaurant',
                plain_message,
                'mochi_restaurant@yahoo.com',
                [from_email, email],
                fail_silently=False,
                html_message=html_message,
            )
            date_formatted = datetime.datetime.strptime(
                customer_requested_date, "%m/%d/%Y")

            # Check to see how many bookings exist at that time/date
            tables_booked = check_table_availabilty(
                customer_requested_time, date_formatted)

            # Get the number of tables in the restaurant
            max_tables = check_table_in_restaurant()

            # Compare number of bookings to number of tables available
            if tables_booked >= max_tables:
                # If the number of tables is bigger than or equal to the
                # max number of tables in the restaurant stop form being
                # submitted

                messages.add_message(
                    request, messages.ERROR,
                    "Unfortunately we are fully booked at "
                    f"{customer_requested_time} on {customer_requested_date}.")
                return render(request, 'Reservation/create_reservation.html', {
                              'customer_form': customer_form,
                                       'form': form})

            else:

                venue = form.save(commit=False)
                venue.user = request.user
                venue.save()
                customer_form.save()
                messages.add_message(
                    request, messages.SUCCESS,
                    f"Thank you {customer_name}, your enquiry for "
                    f"{customer_requested_guests} people at "
                    f"{customer_requested_time} on "
                    f"{customer_requested_date} has been sent.")

                # Return blank forms so the same enquiry isn't sent twice.

                return HttpResponseRedirect('/reserve_table/create_order/')

    return render(request, 'Reservation/create_reservation.html', {
                  'customer_form': customer_form, 'form': form})


@login_required(login_url='/reserve_table/login')
def reserve_table(request):
    """Create function for Reserve a Table """

    orders = request.user.reservation_set.all().order_by('-id')
    if len(orders) == 0:

        # if no reservations
        messages.add_message(request, messages.WARNING,
                             "Sorry, you don't have a any reserved table,"
                             "please reserve here.")

        return HttpResponseRedirect('/reserve_table/create_order/')
    else:
        customers = Customer.objects.all()
        today = datetime.datetime.now().date()
        for reservation in orders:
            if reservation.date < today:
                reservation.status = 'expired'

        context = {
            'orders': orders,
            'customers': customers,
        }

        return render(request, 'Reservation/reservation.html', context)


@login_required(login_url='/reserve_table/login')
def customer_table(request, pk):
    """ Function for get customer id """

    view_booking = Reservation.objects.filter(id=pk)

    context = {
        'view_booking': view_booking,
    }
    return render(request, 'Reservation/view_reservation.html', context)


@login_required(login_url='/reserve_table/login')
def update_reservations(request, pk):
    """ funtion for update booking """

    order = Reservation.objects.get(id=pk)
    form = ReservationForm(instance=order)
    if request.method == 'POST':
        form = ReservationForm(request.POST, instance=order)
        if form.is_valid():
            order.status = 'pending'
            order.table = None
            order.customer = None
            form.save()
            # Send email to the user when user update the booking
            html_message = render_to_string(
                'Reservation/update_booking_email.html',
                {'name': request.user.first_name.capitalize()})
            plain_message = strip_tags(html_message)
            from_email = request.user.email

            send_mail(
                'From: Mochi Restaurant',
                plain_message,
                'mochi_restaurant@site.com',
                [from_email],
                fail_silently=False,
                html_message=html_message,
            )
            messages.add_message(request, messages.SUCCESS, "Thnx, your"
                                 " booking successfully updated.")

            return HttpResponseRedirect('/reserve_table/')

    context = {
        'form': form,
    }
    return render(request, 'Reservation/update_reservation.html', context)


@login_required(login_url='/reserve_table/login')
def delete_reservations(request, pk):
    """ Create funtion for delete single booking in booking list """

    order = Reservation.objects.get(id=pk)
    if request.method == 'POST':
        order.delete()

        # Send email to the user when user deleted the booking
        html_message = render_to_string(
            'Reservation/delete_booking_email.html',
            {'name': request.user.first_name.capitalize()})
        plain_message = strip_tags(html_message)
        from_email = request.user.email

        send_mail(
            'From: Mochi Restaurant',
            plain_message,
            'mochi_restaurant@site.com',
            [from_email],
            fail_silently=False,
            html_message=html_message,
        )
        messages.add_message(
            request, messages.SUCCESS,
            "Thanx, your booking successfully cancelled.")
        return redirect('/reserve_table/')
    context = {
        'item': order,
    }
    return render(request, 'Reservation/delete_reservation.html', context)

reservation/templates/Reservation/create_booking_email.html
{% extends 'mail-templates/mail_reserve_booking.html' %}
{% load static %}
{% block content %}

<h3>Hi {{name}},</h3>
<p>Your booking request has been sent successfully</p>
<p>We will respond to you shortly. Thank you!</p>
<hr />
<h2><strong>Booked By:</strong> mochi-restaurant.herokuapp.com</h2>
<p>If you have any questions,reach out to us at gurpreet.singhb90@gmail.com</p>
<h2>Team Mochi Restaurant</h2>
<hr />
<p>Thanks for visiting mochi-restaurant.herokuapp.com</p>
<hr />
<p>Southall Brodway, UB11RT, London</p>
<p><a href="https://mochi-restaurant.herokuapp.com/">https://mochi-restaurant.herokuapp.com/</a></p>
<img class="email-image" src="https://www.linguahouse.com/linguafiles/md5/d01dfa8621f83289155a3be0970fb0cb"
    alt="email image" />
<p>This email was sent because you joined our retaurant email, online or at one
    of our events . Your email address will not shared with anyone.</p>
<p class="footer-note">
    <strong>&copy; Mochi Restaurant.All Rights Reserved</strong>
</p>
<p class="footer-address">Southall Brodway, UB11RT, London</p>

{% endblock content %}

reservation/templates/Reservation/delete_booking_email.html
{% extends 'mail-templates/mail_reserve_booking.html' %}
{% load static %}
{% block content %}


<h1>Your booking has been canceled. We are really sorry to see you go.</h1>
<h3>Hi {{name}},</h3>
<p> This email confirms that your <a href="https://mochi-restaurant.herokuapp.com/">
        Mochi Restaurant</a> booking has been canceled.</p>
<p>We're really sorry to see you go, but thanks for giving us a try.</p>
<hr />
<h2> mochi-restaurant.herokuapp.com</h2>
<p>If you have any questions,reach out to us at gurpreet.singhb90@gmail.com</p>
<h2>Team Mochi Restaurant</h2>
<hr />
<p>Thanks for visiting mochi-restaurant.herokuapp.com</p>
<hr />
<p>Southall Brodway, UB11RT, London</p>
<p><a href="https://mochi-restaurant.herokuapp.com/">https://mochi-restaurant.herokuapp.com/</a></p>
<img class="email-image" src="https://www.linguahouse.com/linguafiles/md5/d01dfa8621f83289155a3be0970fb0cb"
    alt="email image" />
<p>This email was sent because you joined our retaurant email, online or at one
    of our events . Your email address will not shared with anyone.</p>
<p class="footer-note">
    <strong>&copy; Mochi Restaurant.All Rights Reserved</strong>
</p>
<p class="footer-address">Southall Brodway, UB11RT, London</p>

{% endblock content %}

reservation/templates/Reservation/delete_reservation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ======= Delete Booking Section ======= -->
<section id="book-a-table" class="book-a-table">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Reservation</h2>
      <p>Cancel Your Booking</p>
    </div>
    <div>
      <h4>Are you sure you want to cancel ?</h4>
      <h5>Id {{item.id}}</h5>
      <h5>Persons {{item.persons}}</h5>
      <h5>Time {{item.time}}</h5>
      <h5>Date {{item.date}}</h5>
    </div>

    <form action="{% url 'reservation:delete_reservations' item.id %}" method="POST" role="form">
      {% csrf_token %}
      <a class="btn btn-warning" href="{% url 'reservation:reserve_table' %}">
        Go Back
      </a>
      <input class="btn btn-danger" type="submit" value="Cancel" />
    </form>
  </div>
</section>
<!-- End Delete Booking Section -->

{% endblock content %}

reservation/templates/Reservation/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ======= Login Account Section ======= -->

<section id="book-a-table" class="book-a-table">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Reservation</h2>
      <p>Login Account</p>
    </div>

    <div class="container h-100">
      <div class="input-group justify-content-center mt-4">
        <div class="section-title">
          <p>Login</p>
        </div>
      </div>

      <div class="input-group justify-content-center mb-4">
        {% for message in messages  %}
        <div class="text-danger" style="background-color: #0c0b09;" id="msg">
          <strong>{{ message }}</strong>
        </div>
        {% endfor %}
      </div>

      <form action="" method="POST" role="form">
        {% csrf_token %}
        <div class="row justify-content-center">
          <div class="col-lg-5 col-md-8 mb-4">
            <input type="text" class="form-control shadow-none text-white"
              style="background-color: #0c0b09; border-color:#625b4b" placeholder="Username.." name="username" />
          </div>
        </div>

        <div class="row justify-content-center ">
          <div class=" col-lg-5 col-md-8 mt-4">
            <input type="password" class="form-control shadow-none text-white "
              style="background-color: #0c0b09; border-color:#625b4b" placeholder="Password.." name="password" />
          </div>
        </div>


        <div class="input-group mb-4 justify-content-center mt-4">
          <div class="input-group-append">
            <input type="submit" class="btn-lg btn btn-warning rounded-pill text-white" value="Sign in" />
          </div>
        </div>
        <div class="input-group mb-4 justify-content-center mt-4">
          <p> If you have not created an account yet, then please
            <a href="{% url 'reservation:register' %}"><span class="text-primary">sign up</span></a> first.</p>
        </div>
      </form>
    </div>
  </div>
</section>
<!-- ======= End Login Account Section ======= -->

{% endblock content %}

reservation/templates/Reservation/reservation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ======= Book A Table Section ======= -->
<section id="book-a-table" class="book-a-table">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Reservation</h2>
      <p>Your Booking</p>

      <div class="input-group justify-content-center mb-4">
        {% for message in messages  %}
        <div class="alert alert-success" id="msg">
          <strong>{{ message }}</strong>
        </div>
        {% endfor %}
      </div>
      {% if user.is_authenticated %}
      <div class="bg-dark">
        <div class="row d-flex justify-content-center mb-5">
          <div class="col-sm-12">
            <div class="row d-flex justify-content-center">
              <!-- Each reservation -->
              {% for reservation in orders %}
              <div class="col-md-6 col-lg-4 m-5">
                <div class=" text-center ">
                  <h4>
                    <h4>Reservation ID: {{ reservation.id }} </h4>
                  </h4>
                  <!-- To display '1 person' instead of '1 people' -->
                  {% if reservation.persons == 1 %}
                  <h4>Guests: {{ reservation.persons }} person </h4>
                  {% else %}
                  <h4>Guests: {{ reservation.persons }} people </h4>
                  {% endif %}
                  <h4>Time: {{ reservation.time }} </h4>
                  <h4>Date: <span>{{ reservation.date|date:"d/m/Y"}}</span>
                  </h4>
                  <!-- If reservation has been rejected -->
                  {% if reservation.status == 'rejected' %}
                  <h3 class="mt-3 mb-4 text-danger"> This reservation was
                    <span><strong>{{ reservation.status }}</strong></span>
                    <h3 class="mb-4 text-danger">Sorry you're not able to edit this reservation</h3>
                    <a href="{% url 'reservation:delete_reservations' reservation.id%}"
                      class="button cancel-button inline-btn bg-danger text-white p-2 rounded-pill">Cancel Booking</a>
                    <!-- If reservation has been rejected -->
                    {% elif reservation.status == 'expired' %}
                    <h3 class="mt-3 mb-4 text-danger"> This reservation has
                      <span><strong>{{ reservation.status }}</strong></span>
                    </h3>
                    <h3 class="text-danger mb-4">(Sorry, you're not able to edit this!)</h3>
                    <a href="{% url 'reservation:delete_reservations' reservation.id%}"
                      class="button cancel-button inline-btn bg-danger text-white p-2 rounded-pill">Cancel Booking</a>

                    <!-- For 'confirmed' -->
                    {% elif reservation.status == 'confirmed' %}
                    <h3 class="mt-3 mb-3"> This reservation is <span
                        class="text-success"><strong>{{ reservation.status }}</strong></span>
                    </h3>
                    <div class="text-center">
                      <a href="{% url 'reservation:update_reservations' reservation.id%}"
                        class="button submit-button inline-btn bg-success text-white p-2 rounded-pill">Edit Booking</a>
                      <a href="{% url 'reservation:delete_reservations' reservation.id%}"
                        class="button cancel-button inline-btn bg-danger text-white p-2 rounded-pill">Cancel Booking</a>

                    </div>
                    <div class="text-center mt-5">
                      <a href="{% url 'reservation:customer_table' reservation.id%}"
                        class="button cancel-button inline-btn bg-info text-white p-2 rounded-pill">View Booking</a>
                      <a href="{% url 'reservation:create_order' %}"
                        class="button cancel-button inline-btn bg-info text-white p-2 rounded-pill">New Booking</a>
                    </div>
                    <!-- For 'pending' -->
                    {% else %}
                    <h3 class="mt-3 mb-3"> This reservation is <span
                        class="text-warning"><strong>{{ reservation.status }}</strong></span>
                    </h3>
                    <div class="text-center">
                      <a href="{% url 'reservation:update_reservations' reservation.id%}"
                        class="button submit-button inline-btn bg-success text-white p-2 rounded-pill">Edit Booking</a>
                      <a href="{% url 'reservation:delete_reservations' reservation.id%}"
                        class="button cancel-button inline-btn bg-danger text-white p-2 rounded-pill">Cancel Booking</a>

                    </div>
                    <div class="text-center mt-5">
                      <a href="{% url 'reservation:customer_table' reservation.id%}"
                        class="button cancel-button inline-btn bg-info text-white p-2 rounded-pill">View Booking</a>
                      <a href="{% url 'reservation:create_order' %}"
                        class="button cancel-button inline-btn bg-info text-white p-2 rounded-pill">New Booking</a>
                    </div>
                    {% endif %}
                    <hr>
                    </li>
                </div>
              </div>
              <!-- Show two per row -->
              {% if forloop.counter|divisibleby:2 %}
            </div>
            <div class="row d-flex justify-content-center">
              {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
<!-- End Book A Table Section -->
{% endif %}
{% endblock content %}

reservation/templates/Reservation/view_reservation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ======= View reservation Section ======= -->

<section id="book-a-table" class="book-a-table">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Reservation</h2>
      <p>Your Booking</p>
      {% for message in messages %}
      <div class="input-group justify-content-center mb-4">
        <div class="alert alert-success" role="alert" id="msg">
          <h4 class="alert-heading">{{message}}</h4>
        </div>
      </div>
      <br>
      <br>
      {% endfor %}

      <div class="bg-dark">
        <div class="row d-flex justify-content-center mb-5">
          <div class="col-sm-12">
            <div class="row d-flex justify-content-center">

              <!-- Each reservation -->
              {% for reservation in view_booking %}
              <div class="col-md-6 col-lg-4 m-5">
                <div class=" text-center ">
                  <h4>
                    <h4>Reservation ID: {{ reservation.id }} </h4>
                  </h4>

                  <!-- To display '1 person' instead of '1 people' -->
                  {% if reservation.persons == 1 %}
                  <h4>Guests: {{ reservation.persons }} person </h4>
                  {% else %}
                  <h4>Guests: {{ reservation.persons }} people </h4>
                  {% endif %}
                  <h4>Time: {{ reservation.time }} </h4>
                  <h4 class=" mb-4">Date: <span>{{ reservation.date|date:"m/d/Y"}}</span>
                  </h4>

                  <div class="text-center">
                    <a href="{% url 'reservation:update_reservations' reservation.id%}"
                      class="button submit-button inline-btn bg-success text-white p-2 rounded-pill m-2">Edit
                      Booking</a>
                    <a href="{% url 'reservation:delete_reservations' reservation.id%}"
                      class="button cancel-button inline-btn bg-danger text-white p-2 rounded-pill">Cancel Booking</a>
                  </div>
                  <div class="text-center mt-5">
                    <a href="{% url 'reservation:reserve_table' %}"
                      class="button cancel-button inline-btn bg-info text-white p-2 rounded-pill m-2">Go Back</a>
                    <a href="{% url 'reservation:create_order' %}"
                      class="button cancel-button inline-btn bg-info text-white p-2 rounded-pill">New Booking</a>
                  </div>
                  <hr>
                  </li>
                </div>
              </div>

              <!-- Show two per row -->
              {% if forloop.counter|divisibleby:2 %}
            </div>
            <div class="row d-flex justify-content-center">
              {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
<!-- ======= End View reservation Section ======= -->

{% endblock content %}