aboutRestaurant/urls.py
from django.urls import path
from . import views


app_name = 'aboutRestaurant'

urlpatterns = [

    path('', views.about_us, name='about_us'),


]

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
    path('', views.send_email, name='send_email'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),


]

menu/urls.py
from django.urls import path
from . import views


app_name = 'menu'

urlpatterns = [

    path('', views.meal_list, name='meal_list'),
    path('<slug:slug>/', views.meal_detail, name='meal_detail'),

]

reservation/urls.py
from django.urls import path
from . import views


app_name = 'reservation'

urlpatterns = [

    path('', views.reserve_table, name='reserve_table'),
    path('register/', views.registerpage, name='register'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('create_order/', views.create_order, name='create_order'),
    path('update_reservations/<pk>/', views.update_reservations,
         name='update_reservations'),
    path('delete_reservations/<pk>/', views.delete_reservations,
         name='delete_reservations'),
    path('<pk>/', views.customer_table, name='customer_table'),

]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls', namespace='menu')),
    path('aboutRestaurant/', include('aboutRestaurant.urls',
         namespace='aboutRestaurant')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('reserve_table/', include('reservation.urls', namespace='reservation')),
    path('', include('home.urls', namespace='home')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'home.views.error_404'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="description" content="Mochi Restaurant for who love food in Southall, England">
  <meta name="keywords" content="Mochi Restaurant, england, southall">
  <title>Mochi</title>
  <!-- Favicons -->
  <link href="{% static 'img/restaurant-icon.png'%}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png'%}" rel="apple-touch-icon">
  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i+Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700+Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
    integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous" />
  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/animate.css/animate.min.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- Jquery File -->
  <script src="https://code.jquery.com/jquery-1.8.2.js"></script>
  <script src="https://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
</head>

<body>
  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-phone d-flex align-items-center"><span>02087851220</span></i>
        <i class="bi bi-clock d-flex align-items-center ms-4"><span> Mon-Sat: 11AM - 23PM</span></i>
      </div>
    </div>
  </div>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-cente">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">
      <h2 class="logo me-auto me-lg-0"><a href="{% url 'home:home' %}">Mochi</a></h2>
      <nav id="navbar" class="navbar order-last order-lg-0 ">
        <ul>
          <li><a class="nav-link scrollto" href="{% url 'home:home' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'aboutRestaurant:about_us' %}">About</a></li>
          <li><a class="nav-link scrollto" href="{% url 'menu:meal_list' %}">Menu</a></li>
          <li><a class="nav-link scrollto" href="{% url 'reservation:reserve_table' %}">Your booking</a></li>
          <li><a class="nav-link scrollto" href="{% url 'contact:send_email' %}">Contact</a></li>
          {% if user.is_authenticated %}
          <li class="nav-link scrollto">Hello, {{request.user}}</li>
          <li><a class="nav-link scrollto" href="{% url 'reservation:logout' %}">Logout</a></li>
          {% else %}
          <li><a class="nav-link scrollto" href="{% url 'reservation:login' %}">Login</a></li>
          <li><a class="nav-link scrollto" href="{% url 'reservation:register' %}">Register</a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
      <!-- .navbar -->
      <a href="{% url 'reservation:create_order' %}" class="book-a-table-btn scrollto d-none d-lg-flex">Book a table</a>
    </div>
  </header>
  <!-- End Header -->
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative text-center text-lg-start" data-aos="zoom-in" data-aos-delay="100">
      <div class="row">
        <div class="col-lg-8">
          <h1>Welcome to <span>Mochi</span></h1>
          <h2>Delivering great food for more than 18 years!</h2>
          <div class="btns">
            <a href="{% url 'menu:meal_list' %}" class="btn-menu animated fadeInUp scrollto">Our Menu</a>
            <a href="{% url 'reservation:create_order' %}" class="btn-book animated fadeInUp scrollto">Book a Table</a>
          </div>
        </div>
        <div class="col-lg-4 d-flex align-items-center justify-content-center position-relative" data-aos="zoom-in"
          data-aos-delay="200">
          <a href="https://www.youtube.com/watch?v=7EdpBH81XIY" class="glightbox play-btn"></a>
        </div>
      </div>
    </div>
  </section>
  <!-- End Hero -->
  <main id="main">
    {% block content %}
    {% endblock content %}
  </main>
  <!-- End #main -->
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3>Mochi</h3>
              <p>
                Southall Brodway, UB11RT, London<br />
                <strong>Phone:</strong> 02087851220<br>
                <strong>Email:</strong> mochi@gmail.com<br>
              </p>
              <div class="social-links mt-3">
                <a href="https://www.twitter.com" target="_blank" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="https://www.facebook.com" target="_blank" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="https://www.instagram.com" target="_blank" class="instagram"><i
                    class="bx bxl-instagram"></i></a>
                <a href="https://www.skype.com" target="_blank" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="https://www.linkedin.com" target="_blank" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>
          </div>
          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'home:home' %}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'aboutRestaurant:about_us' %}">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'menu:meal_list' %}">Menu</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'contact:send_email' %}">Contact</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'reservation:create_order' %}">Book a table</a>
              </li>
            </ul>
          </div>
          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Opening Hours</h4>
            <p>Mon-Sat: 11AM - 23PM</p>
            <p>Sun: 12AM - 20PM</p>
            <p>Bank Holidays: Closed</p>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Mochi</span></strong>. All Rights Reserved
      </div>
    </div>
  </footer>
  <!-- End Footer -->
  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>
  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js'%}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js'%}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js'%}"></script>
  <!-- Template Main JS File -->
  <script src="{% static 'js/booking.js'%}"></script>
  <script src="{% static 'js/update.js'%}"></script>
  <script src="{% static 'js/datepicker.js'%}"></script>
  <script src="{% static 'js/contact.js'%}"></script>
  <script src="{% static 'js/main.js'%}"></script>
</body>

</html>